import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {ClassicLevel} from 'classic-level';
import {skillDocument} from '../module/library.js';
import {crestDocuments} from '../module/crest.js';
const catalog=JSON.parse(await fs.readFile('data/skills.json','utf8'));
const id=key=>createHash('sha256').update(key).digest('hex').slice(0,16);
const groups=[{name:'color-skills',type:'color'},{name:'flower-skills',type:'flower'},{name:'special-skills',type:''}];
for(const pack of groups){
 const directory=path.join('packs',pack.name);await fs.rm(directory,{recursive:true,force:true});
 const db=new ClassicLevel(directory,{keyEncoding:'utf8',valueEncoding:'utf8'});
 try{
  const documents=[...crestDocuments(catalog).filter(d=>d.type===pack.type),...catalog.map(r=>skillDocument(r)).filter(d=>d.system.parentType===pack.type)];
  const folders=[...new Set(documents.map(d=>d.type==='ability'?d.system.parentKey||'Special':d.system.key))].sort();
  const entries=folders.map((name,sort)=>({type:'put',key:`!folders!${id(pack.name+':'+name)}`,value:JSON.stringify({_id:id(pack.name+':'+name),name,type:'Item',folder:null,sorting:'a',sort,flags:{}})}));
  for(const data of documents){
   const key=data.type==='ability'?data.system.parentKey||'Special':data.system.key;
   const document={...data,_id:id(data.type+':'+data.system.key),folder:id(pack.name+':'+key),sort:data.type==='ability'?100000:0,flags:{}};
   entries.push({type:'put',key:`!items!${document._id}`,value:JSON.stringify(document)});
  }
  await db.batch(entries);await db.compactRange('','~');
  console.log(`${pack.name}: ${documents.filter(d=>d.type==='ability').length} Skills, ${documents.filter(d=>d.type!=='ability').length} Parents, ${folders.length} folders`);
 }finally{await db.close();}
 // These files are regenerated by LevelDB and are not release data.
 for(const name of await fs.readdir(directory))if(name==='LOCK'||name==='LOG'||name==='LOG.old')await fs.rm(path.join(directory,name));
}

// Stage Actors include editable Set/Omen routines and their native Skill Items.
{
 const {stageDocument}=await import('../module/stage-data.js');
 const records=JSON.parse(await fs.readFile('data/stages.json','utf8'));
 const directory='packs/stages';await fs.rm(directory,{recursive:true,force:true});
 const db=new ClassicLevel(directory,{keyEncoding:'utf8',valueEncoding:'utf8'});
 try{await db.batch(records.map(record=>{
   const actor=stageDocument(record);actor._id=id('stage:'+record.id);actor.folder=null;actor.ownership={default:2};actor.flags={};
   actor.items=actor.items.map(item=>({...item,_id:id(item.system.key),folder:null}));
   return {type:'put',key:`!actors!${actor._id}`,value:JSON.stringify(actor)};
 }));await db.compactRange('','~');}finally{await db.close();}
 for(const name of await fs.readdir(directory))if(['LOCK','LOG','LOG.old'].includes(name))await fs.rm(path.join(directory,name));
 console.log(`stages: ${records.length} Stage Actors with Set and Omen Skill Items`);
}
