import fs from 'node:fs';
import path from 'node:path';
fs.mkdirSync('artifacts', {recursive:true});
import Handlebars from 'handlebars';
const skills=JSON.parse(fs.readFileSync('data/skills.json'));
const lang=JSON.parse(fs.readFileSync('lang/th.json'));
Handlebars.registerHelper('localize',key=>lang[key]??key);
Handlebars.registerHelper('checked',value=>value?'checked':'');
Handlebars.registerHelper('selectOptions',(choices,options)=>{
 const selected=options.hash.selected;
 const list=Array.isArray(choices)?choices.map(c=>typeof c==='object'?{value:c[options.hash.valueAttr],label:c[options.hash.labelAttr]}:{value:c,label:c}):Object.entries(choices??{}).map(([value,label])=>({value,label}));
 return new Handlebars.SafeString(list.map(c=>`<option value="${Handlebars.escapeExpression(c.value)}" ${c.value===selected?'selected':''}>${Handlebars.escapeExpression(c.label)}</option>`).join(''));
});
const docs=skills.filter(s=>['knights-etiquette','pride-roses','purifying-rose','royal-rose-dress','night-runner','midnight-vamp'].includes(s.id)).map((s,i)=>({id:s.id,name:s.name,system:{type:s.group,timing:s.timing,page:s.page,effect:s.text,charge:[2,1,0,1,0,2][i],number:i+1}}));
const image='data:image/svg+xml;base64,'+fs.readFileSync('assets/emblem.svg').toString('base64');
const actor={name:'Tsubaki · Bringer',img:image,type:'bringer'};
const system={hp:{value:18,max:16},defense:{value:3},charge:{value:3},garden:2,bouquet:32,exp:7,distortion:1,flames:0,details:{age:'17',sex:'หญิง',career:'St. Argetia Academy',partner:'s',crest:{color:'Black',flower:'Rose'},karma:{type:'hope',detail:'I’ll protect you'},wish:'ปกป้องทุกวันธรรมดาที่ได้อยู่ด้วยกัน',wishTier:2,personality:{first:'สุขุม',second:'อ่อนโยน'},keyword:'Heart, Activate!',weapon:'Silver sword',dress:'กลีบกุหลาบสีดำ',biography:'แผ่นตัวละครใช้โครงสร้างข้อมูลจากโปรเจกต์เดิม พร้อมเพิ่มระบบ Foundry v14'}};
const ctx={actor,system,fighter:true,enemy:false,status:'รอแสดง',derivedDefense:3,medalsRequired:12,partners:[{id:'s',name:'Hakua · Sheath'}],colors:['Black','Red','Yellow','Blue','White','Purple'],flowers:['Rose','Columbine','Cosmos','Morning Glory','Anemone','Spider Lily','Amaranthus'],karmaChoices:{hope:'ความหวัง',despair:'ความสิ้นหวัง'},slots:docs.map((item,i)=>({number:i+1,item})),items:docs};
const html=Handlebars.compile(fs.readFileSync('templates/bringer-sheet.html','utf8'))(ctx);
const css=fs.readFileSync('styles/stella.css','utf8')+fs.readFileSync('styles/v14.css','utf8');
fs.writeFileSync(path.resolve('artifacts/stellaknights-preview.html'),`<!doctype html><html lang="th"><meta charset="utf-8"><title>Stella Knights v14 — layout preview</title><style>body{margin:0;background:#253144;font:14px sans-serif;padding:22px}*{box-sizing:border-box}.preview-note{max-width:860px;margin:auto auto 14px;color:#fff;font:13px sans-serif}.stella-v14{max-width:860px;margin:auto;background:#f7f1e8;padding:20px;border-radius:12px}input,select,textarea,button{font:inherit}table{width:100%}</style><style>${css}</style><div class="preview-note">Static layout preview · Foundry VTT v14 adaptation of ksx0330/FVTT-StellaKnights-System · Not a Foundry runtime test</div><form class="stella stella-v14">${html}</form></html>`);
console.log(path.resolve('artifacts/stellaknights-preview.html'));
